// src/lib/components/Experience.svelte
<script lang='ts'>
    let {title, company, tags, description} = $props();
</script>

<div class="rounded-lg overflow-hidden border-2 border-black bg-white">
    <div class="p-6">
      <div class="flex flex-col mb-4">
        <h2 class="text-xl font-bold text-gray-800">{title}</h2>
        <h3 class="text-md font-semibold text-gray-600">{company}</h3>
      </div>
      <div class="mb-4">
        {#each tags as tag}
          <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
            {tag}
          </span>
        {/each}
      </div>
      <ul class="list-disc list-inside text-md">
        {#each description as descriptionPoint}
          <li>{descriptionPoint}</li>
        {/each}
      </ul>
    </div>
  </div>

// src/components/Experience.jsx
const Experience = ({ experience }) => {
  return (
    <div className="max-w-3xl bg-white rounded overflow-hidden shadow-lg text-left ease-in-out duration-500 hover:drop-shadow-2xl">
      <div className="px-6 py-4">
        <div className="font-bold text-xl mb-2">
          <h1 className="ease-in-out duration-300">
            {experience.title} - {experience.company}
          </h1>
        </div>
        {experience.details.map((point, index) => (
          <li key={index} className="text-gray-700 text-base">
            {point}
          </li>
        ))}
      </div>
      <div className="px-6 pt-4 pb-2">
        {experience.tags.map((tag, index) => (
          <span
            key={index}
            className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"
          >
            {tag}
          </span>
        ))}
      </div>
    </div>
  );
};

export default Experience;
